# Site settings
title: Un peu de math
email: vincent.knight@gmail.com
description: "I post stuff here about game theory, queueing theory, Sage, Python and other things..."
baseurl: ""
url: "http://yourdomain.com"
username: "@drvinceknight"

# Build settings
markdown: kramdown
permalink: pretty
