# Site settings
title: Un peu de math
email: vincent.knight@gmail.com
description: "I post stuff here about game theory, queueing theory, pedagogy, Sage, Python and other things..."
baseurl: "/unpeudemath"
url: "http://drvinceknight.github.io"
github_username: "drvinceknight"
twitter_username: "@drvinceknight"
plus_username: "+VincentKnight"

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
paginate: 5

gems: [jekyll-paginate]

collections:
- notebooks
