# Site settings
title: Un peu de math
email: vincent.knight@gmail.com
description: "I post stuff here about game theory, queueing theory, Sage, Python and other things..."
baseurl: "/unpeudemath"
url: "http://drvinceknight.github.io/unpeudemath/"
github_username: "drvinceknight"
twitter_username: "@drvinceknight"
plus_username: "+VincentKnight"

# Build settings
markdown: kramdown
permalink: pretty
